version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    environment:
      - SERVER_NAME=:80
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      # - SERVER_NAME=${DOMAIN_NAME}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=debug
    volumes:
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      # - caddy_data:/data
      # - caddy_config:/config
    depends_on:
      - db
    networks:
      - proxy_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`perpustakaan-al-maruf.my.id`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=myresolver"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true

volumes:
  db_data:
  # caddy_data:
  # caddy_config:
